version: 2
updates:
  # 1. Dependabot Automated Dependency Security Updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "security"
      - "npm"
    assignees:
      - "Shakibul-CyberSec"

  # 2. GitHub Actions Workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
